<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MaidenheadLib" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\chirpcsvlib\chirpcsvlib.csproj" />
    <ProjectReference Include="..\DotNetCoords\DotNetCoords.csproj" />
  </ItemGroup>

</Project>
