<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>radiodata_ui</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AmateurBandLib" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\chirpcsvlib\chirpcsvlib.csproj" />
    <ProjectReference Include="..\ukrepeaterlib\ukrepeaterlib.csproj" />
  </ItemGroup>

</Project>
